### ISSUE TITLE
Client binaries (or in a container)

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/deployment-manager#109]
If you're running against a GKE cluster, you're exceedingly unlikely to even have a Go setup. We don't want to force this on people. `dm` should be available in binary form, probably coming off a continuous integration system and then with real release tags.

You might also be able to distribute a container with the dm binary in it that anyone could `docker run` with templates injected via volume, resolving the annoyance of multi-arch support.

**Comment by jackgr** [comment]
We should be able to close out this issue shortly per #128.

**Comment by runseb** [comment]
I disagree that it should run in a container. dm is a simple binary, we can provide a cross-compiled version and make it available for direct download just like kubectl.

**Comment by zmerlynn** [comment]
Containers also solve a distribution/tagging problem, too, though. (Or introduce one, if the dm client isn't interoperable with the dm bits you deployed.)

**Comment by bmelville** [comment]
Agree on both counts. However running in a container proves more complex
given that the dm client really wants to be able to talk to the local file
system in many use cases.

**Comment by runseb** [comment]
Running dm in a container seems like overhead to me, we can build a static binary for dm and cut a release easily. Since the manager is deployed as services,rc, the only thing users need is the dm cli. Just like kubectl. 
In the end dm cli could actually be part of kubectl. just my 2 cats

**Comment by jackgr** [comment]
@runseb I'd like to find a way to make kubectl totally agnostic to templating solutions. Giving it a way to invoke a service in the cluster is a nice idea. It needn't be wired to dm, per se.

At this point, however, there are a lot of competing proposals, such as [Red Hat's templates API](https://github.com/kubernetes/kubernetes/pull/18215#issuecomment-163798164) and the client side proposals from @brendandburns (kubernetes/kubernetes#14993 and kubernetes/kubernetes#14918).
