### ISSUE TITLE
Assymetry between create and delete is odd

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/deployment-manager#110]
After I do: `dm deploy redis:v1`

I'm not expecting this:
```console
$ dm list
[
  "redis-v1"
]
```

Nor am I expecting to have to delete it via:
```console
$ dm delete redis-v1
```

I'd expect to delete `redis:v1`, like I created it.

ETA: I admit I'm probably missing something obvious.

**Comment by bmelville** [comment]
Yes this is a little weird. We can probably name the deployment exactly after the type in this case to make things better.
