### ISSUE TITLE
Schema property defaults does not work

### ISSUE THREAD

**Issue by bmelville** [kubernetes/deployment-manager#112]
This is a known issue in the expansion python code, and is being worked on separately by @grahamawelch

**Comment by zmerlynn** [comment]
Oh, good. I was just about to ask why the defaults were specified in both the `.jinja` and the `.jinja.schema`

**Comment by grahamawelch** [comment]
Fixed a while ago with https://github.com/kubernetes/deployment-manager/commit/6e15ece72444f2dc53663f6becfc8bde41c12784
