### ISSUE TITLE
Travis didn't catch a breakage introduced in #133

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes/deployment-manager#146]
Figure out why travis did not catch breakage caused by #133.
Any ideas @goltermann

**Comment by goltermann** [comment]
Travis ran, and did see failures (https://travis-ci.org/kubernetes/deployment-manager/builds/93833882).  Going to look into why "make test" returns 0 in that case.

**Comment by goltermann** [comment]
Looks like the "-" that prepends the "go test" line at https://github.com/kubernetes/deployment-manager/blob/master/Makefile#L21 means "ignore output exit code".

I'll get a PR together to fix it.

**Comment by vaikas-google** [comment]
Aha. I wonder if it's because the makefile has a minus sign in front of the go test? I think that means it ignores the exit status and will continue.

@jackgr thoughts?

Although, I do recall that in other instances where there have been failures and travis has flagged them. So, perhaps that's not the case.

**Comment by jackgr** [comment]
Yes, that's correct. The minus sign means to ignore the result. We should
remove it, now that we have automated builds.

Jack Greenfield | Google
