### ISSUE TITLE
Accept native Kubernetes manifests as configuration files

### ISSUE THREAD

**Issue by jackgr** [kubernetes/deployment-manager#157]
Currently, we require the configuration supplied to dm to be in the dm configuration format (i.e., a list of resources, each of which has a name, a type and a list of parameters), and we throw an unmarshalling error if it isn't. In order to integrate with helm, or just to support a simpler experiences, dm should accept a flat list of native Kubernetes manifests as an alternative form of configuration.

**Comment by vaikas-google** [comment]
Added support for this in #166
