### ISSUE TITLE
Make a release of dm

### ISSUE THREAD

**Issue by runseb** [kubernetes/deployment-manager#161]
Would be great to create a rc release of the dm client. That way we can grab it easily, instead of building from source.

Also we need a cross-compilation setup for dm

**Comment by zmerlynn** [comment]
I opened #109 for this (and I think they're doing with the container suggestion, because it's expedient).

**Comment by runseb** [comment]
@zmerlynn I don't think it should be in a container. so I commented on #109 thanks for link
