### ISSUE TITLE
Private registries

### ISSUE THREAD

**Issue by alialaee** [kubernetes/deployment-manager#181]
There is no way to host a private registry at the moment. I suggest the following proposal:

Using following format as the url pointing to a registry:
	http://[auth-token@]company.com/[...]/
When dm make a request to this url (with auth token transferred to http auth header)  it will receive a list of types and their corresponding data. This could be like this: 

```
{
	"name": "application-dm-templates",
	"description": "Curated applications for Kubernetes using Deployment Manager templates",
	"types": {
		"storage/redis:v1": {
			"url": "http://raw.githubusercontent.com/kubernetes/application-dm-templates/tree/master/storage/redis/v1",
			"title": "Redis cluster",
			"description": "Defines a redis cluster, using a single replica",
			"sha256": "49b45aa2a145726a8ac64b7a5bad1f13c898d3f9d6ec7d4b3735233dd18ef596"
		},
		...
	}
}
```
This file could be generated dynamically or served statically. If there is enough interest I would like to work on it.

**Comment by jackgr** [comment]
@alialaee PTAL at #214. Does it address this issue?

**Comment by alialaee** [comment]
@jackgr It does. Thanks.
