### ISSUE TITLE
replicated_service template was broken by some change to k8s.

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes/deployment-manager#188]
vaikas@vaikas-glaptop:~/projects/dmos/src/github.com/kubernetes/deployment-manager$ dm --service=http://localhost:8080 deploy examples/guestbook/guestbook.yaml 
2016/01/26 10:02:35 cannot deploy configuration named guestbook.yaml: status code: 400 status: 400 Bad Request : Found resource errors during deployment: [kubectl failed for resource: frontend-service: exit status 1: error validating "STDIN": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false
 kubectl failed for resource: redis-master: exit status 1: error validating "STDIN": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false
 kubectl failed for resource: redis-slave: exit status 1: error validating "STDIN": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false
]

Cluster information:
vaikas@vaikas-glaptop:~/projects/dmos/src/github.com/kubernetes/deployment-manager$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}

And the relevant bits about the ports seems to be here:
http://kubernetes.io/v1.0/docs/user-guide/services.html#type-nodeport

@bmelville

**Comment by bmelville** [comment]
Looks like this works for 1.1 k8s service version:

Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}

Did you try turning it off and on again?
