### ISSUE TITLE
Swap out registry/semver.go for a third party SemVer package

### ISSUE THREAD

**Issue by jackgr** [kubernetes/deployment-manager#206]
There are many third party packages that provide support for SemVer. Most of them provide more functionality than registry/semver.go, such as sorting, range checking, etc. The package recommended by Go Academy is [github.com/Masterminds/semver](https://github.com/Masterminds/semver).

**Comment by sgoings** [comment]
See also #216

**Comment by jackgr** [comment]
Closing as duplicate of #216.
