### ISSUE TITLE
Add active contributors to deployment-manager-collaborators team

### ISSUE THREAD

**Issue by jackgr** [kubernetes/deployment-manager#288]
As we prepare to merge the helm repo into this repo, we need to make the active contributors members of the @kubernetes/deployment-manager-collaborators team. Here are their Github handles: @runseb, @sparkprime.

**Comment by jackgr** [comment]
Depends on #289.

**Comment by vaikas-google** [comment]
done.

**Comment by jackgr** [comment]
Thanks, @vaikas-google!
