### ISSUE TITLE
Inject install.yaml into the helm binary prior to build

### ISSUE THREAD

**Issue by adamreese** [kubernetes/deployment-manager#306]

**Comment by technosophos** [comment]
One thing we could do is maintain the YAML file as a separate artifact, and then inject it into the binary at build time.

**Comment by jackgr** [comment]
And make it overridable on the command line.

**Comment by technosophos** [comment]
So after testing a few things, this is clearly not the ideal solution to the problem. The manifest changes in very predictable ways -- most notably, the image field changes with each build. Maintaining this in a static text file is suboptimal. And then when we add in the process of importing that into the source code, it gets really cumbersome.

In contrast, embedding the file inside of the library and altering it to be a Go template means we can very easily parameterize it (which is more in step with our philosophy). I think I am going to experiment with that route for a bit.
