### ISSUE TITLE
Better Travis response times?

### ISSUE THREAD

**Issue by technosophos** [kubernetes/deployment-manager#321]
We seem to be sharing a Travis queue with Kubernetes. Is there a way around that?

**Comment by michelleN** [comment]
Linking @jackgr in on this for any advice here.

**Comment by jackgr** [comment]
I suppose there is, if we want to pay for our own subscription. :0(

**Comment by technosophos** [comment]
I'm at 4h15m waiting for Travis to do a single test run.

**Comment by goltermann** [comment]
Which PR?

https://travis-ci.org/kubernetes/deployment-manager/requests seems healthy, but I'm on mobile, so maybe I'm missing something.

**Comment by goltermann** [comment]
Oh, never mind, I see #317 was the last to actually run and pass.  That's pretty bad.

**Comment by jackgr** [comment]
@goltermann any idea what it would cost us to have our own queue?

**Comment by goltermann** [comment]
For what it's worth, I asked around, and we think the bug isn't from DM sharing with Kubernetes, but from what appears to be a global Travis limit (https://www.traviscistatus.com/ -> Active Linux Builds for Open Source projects (GCE) graph appears to be pegged at 250).

**Comment by jackgr** [comment]
@goltermann Thanks for checking. Sounds like we need to ditch Travis.

Any suggestions as to what we might use instead? How's Shippable working out? Also, #327 suggests CircleCI.

**Comment by technosophos** [comment]
Closed by #333.
