### ISSUE TITLE
Test CircleCI as an alternative to Travis

### ISSUE THREAD

**Issue by technosophos** [kubernetes/deployment-manager#327]
In an effort to completely work around the Kubernetes Travis sharing, maybe we should test CircleCI. Travis is turning out to be a formidable hinderance to productivity.

**Comment by technosophos** [comment]
Whoever turned on CircleCI... THANK YOU! The dummy test runs in under a minute.

**Comment by jackgr** [comment]
Is CircleCI running now?

**Comment by technosophos** [comment]
Closed by #333
