### ISSUE TITLE
Clean up hack/dm-push.sh and get-install.sh

### ISSUE THREAD

**Issue by technosophos** [kubernetes/deployment-manager#336]
Per @runseb  in issue #332: 

> might want to change the README , the get-install.sh and the hack/dm-push.sh as well

Per @jackgr in issue #332:

> Yes, change README text regarding install.yaml, but don't think we need to clean up get-install.sh and hack/dm-push.sh in this PR.

**Comment by runseb** [comment]
Now that we can install dm with `helm dm install` the dm-push script should include the helm client. Which means the get-install script should also deal with it.

The main README is not in sync with the new `helm dm install` workflow.

Happy to submit a PR for this if we think this is the right direction.

**Comment by sgoings** [comment]
Talked this through - more details and a more specific issue: #378.
