### ISSUE TITLE
redis:v1 Example Missing Properties in Expansion

### ISSUE THREAD

**Issue by goltermann** [kubernetes/deployment-manager#35]
$ dm deploy redis:v1
2015/11/11 11:25:34 cannot deploy template named : status code: 400 status: 400 Bad Request : cannot expand template named  (template expansion:expander service response:&{400 Bad Request 400 HTTP/1.1 1 1 map[Date:[Wed, 11 Nov 2015 19:25:34 GMT] Content-Length:[622] Content-Type:[text/plain; charset=utf-8]] 0xc20824e300 622 [] false map[] 0xc208033ad0 <nil>}
):
resources:
- name: redis:v1
  type: https://raw.githubusercontent.com/kubernetes/deployment-manager/master/types/redis/v1/redis.jinja

$ kubectl logs expandybird-rc-dj2di
2015/11/11 19:22:27 expandybird: expand: handling request:POST /expand
2015/11/11 19:22:28 Expansion process: pid: 14 SysTime: 20ms UserTime: 84ms
2015/11/11 19:22:28 expandybird: expand: returning response: status code:400, status:error (error expanding template : Traceback (most recent call last):
  File "./expansion/expansion.py", line 372, in <module>
    main()
  File "./expansion/expansion.py", line 369, in main
    print Expand(template, imports, env=env, validate_schema=validate_schema)
  File "./expansion/expansion.py", line 57, in Expand
    raise ExpansionError('config', str(e))
__main__.ExpansionError: 'properties' is undefined Resource: config
) expanding template:
&{ resources:
- name: redis:v1
  type: https://raw.githubusercontent.com/kubernetes/deployment-manager/master/types/redis/v1/redis.jinja
 [0xc820010cc0 0xc820010ce0]}

**Comment by jackgr** [comment]
@goltermann What is the status of this issue? Is there a PR under development to fix it?

**Comment by goltermann** [comment]
Worked on it a bit today, but didn't get to the bottom of it.  I'm out tomorrow, so if someone wants to pick it up, go for it.  If it's still around, I'll look again Friday.

**Comment by bmelville** [comment]
I'm happy to pick this up tomorrow.

**Comment by bmelville** [comment]
This was just a template issue. Unfortunately the jinja library gives pretty bad error messages during expansion.

@vagababov will hopefully help us improve the error messages from jinja.
