### ISSUE TITLE
dm client doesn't allow me to specify a deployment name

### ISSUE THREAD

**Issue by bmelville** [kubernetes/deployment-manager#36]
I need to be able to specify a deployment name when deploying a type or config.

This should probably be dm deploy <deployment name> <type | template> so deployment name is in the same position as get, etc.

**Comment by bmelville** [comment]
cc @vaikas-google @jackgr 

We have a few options:

1) dm deploy <name> redis:v1
2) dm deploy redis:v1 <name>
3) dm --name <name> deploy redis:v1

Jack has a comment about supporting STDIN, which would work well for templates (e.g., dm deploy name <foo.yaml)

What do you guys think?

**Comment by jackgr** [comment]
Currently, the name is defaulted from the template, if you've provided a template. If you deploy a type, then we construct the template automatically, so there is no template name that can be used to name the deployment. It's easy enough to generate a time stamp based name in this case, using the type name as a prefix (e.g., redis:v1:XXXXXXXX).

However, this issue raises a question in my mind. Does the caller really want to name a deployment? Would it be sufficient to let DM always generate a name?

**Comment by jackgr** [comment]
If we decide that callers really want to name their deployments, then I'd opt for:

4) dm --name=MyName deploy redis:v1

Also, not that the stdin scenario requires a flag:

5) dm --stdin deploy

**Comment by bmelville** [comment]
They definitely will, e.g., running multiple redis clusters in a cluster,
running multiple replicatedservices in a single cluster. Right now these
are all just named after the type.

We can defer on the stdin piece for now, but we could either do flag or
have it look to STDIN if a type or template isn't provided perhaps.

**Comment by jackgr** [comment]
Clearly, deployments need unique names. I was asking whether the customer wants to specify those names, or would be happy with having them automatically generated?

STDIN should be for the template content, not just for the name.

**Comment by bmelville** [comment]
I think typically a user wants to name their deployment, as they need to differentiate between possibly many deployments with similar architectures when they are doing things like update and delete.

If I were to list deployments and get a bunch of "deployment-XXXXXXX", I would have to dig into them all to find the one I'm actually looking for.

**Comment by jackgr** [comment]
Another approach would be to use labels to capture that information. If we took that approach, then the label values could be passed in as parameters.

That said, I get the point. Users want to name deployments.
