### ISSUE TITLE
Error not propagated when resource already exists during deployment

### ISSUE THREAD

**Issue by bmelville** [kubernetes/deployment-manager#37]
$ dm --service=http://localhost:8080 deploy types/redis/v1/redis.yaml
2015/11/11 15:37:20 cannot deploy template named redis.yaml: status code: 400 status: 400 Bad Request : cannot create configuration (deployer service response:
&{400 Bad Request 400 HTTP/1.1 1 1 map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff] Date:[Wed, 11 Nov 2015 23:37:20 GMT] Content-Length:[618]] 0xc82000e360 618 [] false map[] 0xc82040a000 <nil>}
)

$ cat log/manager.log
2015/11/11 15:37:14 Version: 0.0.1
2015/11/11 15:37:14 Listening on port 8080...
2015/11/11 15:37:16 manager: create deployment: handling request:POST /deployments
2015/11/11 15:37:16 manager: create deployment: handling request:POST /deployments
2015/11/11 15:37:16 Creating deployment: redis.yaml
2015/11/11 15:37:17 created deployment: &{redis.yaml 1 2015-11-11 15:37:17.613537833 -0800 PST 2015-11-11 15:37:17.613538146 -0800 PST 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC Creat t/r/v/redis.yaml  d/dm.go                                                                         X
ed <nil> map[]}
2015/11/11 15:37:17 Added manifest manifest-1447285037613578429 to deployment: redis.yaml
2015/11/11 15:37:20 deleted deployment: &{redis.yaml 1 2015-11-11 15:37:17.613537833 -0800 PST 2015-11-11 15:37:17.613538146 -0800 PST 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC Created <nil> map[manifest-1447285037613578429:0xc82049ab00]}
2015/11/11 15:37:20 manager: create deployment: returning response: status code:400, status:cannot create configuration (deployer service response:
&{400 Bad Request 400 HTTP/1.1 1 1 map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff] Date:[Wed, 11 Nov 2015 23:37:20 GMT] Content-Length:[618]] 0xc82000e360 618 [] false map[] 0xc82040a000 <nil>}
)
::1 - - [11/Nov/2015:15:37:16 -0800] "POST /deployments HTTP/1.1" 400 282 "" "Go-http-client/1.1"

$ cat log/resourcifier.log
2015/11/11 15:37:14 Version: 0.0.1
2015/11/11 15:37:14 Listening on port 8082...
2015/11/11 15:37:17 resourcifier: create configuration: handling request:POST /configurations
2015/11/11 15:37:18 kubetcl failed for resource: redis-master: exit status 1: Error from server: error when creating "STDIN": service "redis-master" already exists

2015/11/11 15:37:18 kubetcl failed for resource: redis-master-rc: exit status 1: Error from server: error when creating "STDIN": replicationControllers "redis-master-rc" already exists

2015/11/11 15:37:19 kubetcl failed for resource: redis-slave: exit status 1: Error from server: error when creating "STDIN": service "redis-slave" already exists

2015/11/11 15:37:20 kubetcl failed for resource: redis-slave-rc: exit status 1: Error from server: error when creating "STDIN": replicationControllers "redis-slave-rc" already exists

2015/11/11 15:37:20 resourcifier: create configuration: returning response: status code:400, status:kubetcl failed for resource: redis-master: exit status 1: Error from server: error when creating "STDIN": service "redis-master" already exists

kubetcl failed for resource: redis-master-rc: exit status 1: Error from server: error when creating "STDIN": replicationControllers "redis-master-rc" already exists

kubetcl failed for resource: redis-slave: exit status 1: Error from server: error when creating "STDIN": service "redis-slave" already exists

kubetcl failed for resource: redis-slave-rc: exit status 1: Error from server: error when creating "STDIN": replicationControllers "redis-slave-rc" already exists

::1 - - [11/Nov/2015:15:37:17 -0800] "POST /configurations HTTP/1.1" 400 618 "" "Go-http-client/1.1"

**Comment by jackgr** [comment]
Fixed by #40.
