### ISSUE TITLE
Deployments should have resource objects with resource metadata

### ISSUE THREAD

**Issue by bmelville** [kubernetes/deployment-manager#80]
A deployment needs to have information about the resources created:

- status of resource (created, failed, aborted)
- error messages
- RESTful identifier/link to the actual resource created
- name, type, properties

**Comment by vaikas-google** [comment]
These (and errors in #79) could be part of Deployment, or part of a Manifest. If they are part of a Manifest, you would have one stop shop for: input, fully expanded low level config as well as the output [resources/errors]. Unless I hear strong arguments against putting them there, I'd like to at least take a whack at putting them there.
