### ISSUE TITLE
Create new repository in the kubernetes Github organization

### ISSUE THREAD

**Issue by jackgr** [kubernetes/deployment-manager#87]
The name of the repository should be `application-dm-templates` per kubernetes/kubernetes#17027. The owners should be the owners of `deployment-manager`. It should have a `maintainers` group with write privileges and a `collaborators` group. This is a prerequisite for #82.

**Comment by vaikas-google** [comment]
Created:
https://github.com/kubernetes/application-dm-templates

Added deployment-manager-maintainers as having write access just like kubernetes/deployment-manager

**Comment by jackgr** [comment]
We probably want a different maintainers group, so that we can give different community members write access to the content and the code.

**Comment by vaikas-google** [comment]
Aren't those collaborators?

**Comment by jackgr** [comment]
No. We want to give people maintainer rights for just the content.

Jack Greenfield | Google

**Comment by vaikas-google** [comment]
Ok, well, you should be a maintainer so can you just set it up the way you
want it set up? :)

**Comment by jackgr** [comment]
Unfortunately, it doesn't work that way.

What we need is a team called application-dm-templates-maintainers, so that we can add community members to it as they gain committer rights to the content. This will be a different set of people than the members of deployment-manager-maintainers.

We'll also want an application-dm-templates-collaborators team, which will be populated with interested parties known the repository with read only access to the content. This will be a different set of people than the members of deployment-manager-collaborators, who have the same kind of interest in the code, rather than the content.

Teams can only be created by owners of the Kubernetes organization. Those are also the only people who can create repositories. Since you had permissions to create the repository, and I didn't, you're an owner of the organization, and I'm not. You therefore have permissions to create the teams in question, and I don't.

**Comment by vaikas-google** [comment]
Ok, it was just not clear from the bug that a new team was needed to be
created and relied on naming convention. I'll take a whack at it...
So, create two teams:
 application-dm-templates-maintainers
 application-dm-templates-collaborators

Correct?

**Comment by jackgr** [comment]
Correct.

Jack Greenfield | Google

**Comment by vaikas-google** [comment]
Ok, done and made you a maintainer on both. Better?

**Comment by jackgr** [comment]
You're the man.
