### ISSUE TITLE
Cannot delete deployment with empty name

### ISSUE THREAD

**Issue by goltermann** [kubernetes/deployment-manager#89]
Currently if I dm deploy redis:v1, it creates a deployment with an empty string for a name.  Then I can't dm delete it:

$ dm list
["","guestbook.yaml"]
$ dm delete ""
2015/11/17 13:45:59 cannot delete deployment named : status code: 404 status: 404 Not Found : 404 page not found

Related to #36.  We should disallow empty deployment names.

**Comment by bmelville** [comment]
Just noticed this as well. I'm working in this space for naming stuff and can take this.
